### ISSUE TITLE
Release version contains `-DIRTY` suffix on Maven Central

### ISSUE THREAD

**Issue by kyri-petrou** [Iltotore/iron#103]
Hi there 👋  It seems that the `2.0.0-RC3` release was released as `2.0.0-RC3-DIRTY12775d8a` on Maven Central. Weirdly enough, this also happened with `2.0.0-RC2` which has 2 releases (one with and one without the -DIRTY suffix

**Comment by Iltotore** [comment]
Hello.

Thank you for this issue. I yesterday investigated this problem just after releasing (this kind of action is hard to test !) and I think I found the cause.
