### ISSUE TITLE
Cannot refine non full inlined input at compile-time

### ISSUE THREAD

**Issue by chuwy** [Iltotore/iron#105]
**Describe the bug**
Scala environment: JVM
Scala version: 3.2.2
Iron version: 2.0.0

**Reproduction steps**

```scala
import io.github.iltotore.iron.*
import io.github.iltotore.iron.constraint.string.*

def test[F[_]: Concurrent](str: String): F[Result] =
  for {
    id <- Concurrent[F].fromEither(Either.catchNonFatal(str.refine[Alphanumeric]))
    result <- doSomething(id)
  } yield result
```

**Expected behavior**
This should compile.

**Current behavior**

Throws a compile-time error:

```
[error] 215 |            result <- doSomething(id)
[error]     |                                  ^^
[error]     |Cannot refine non full inlined input at compile-time.
[error]     |To test a constraint at runtime, use the `refined` extension method.
[error]     |
[error]     |Note: Due to a Scala limitation, already-refined types cannot be tested at compile-time (unless proven by an `Implication`).
[error]     |
[error]     |Inlined input: id
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Postgres.scala:215
[error]      ---------------------------------------------------------------------------
```

Also, I couldn't find method `inlined` (with `d` at the end)

**Comment by Iltotore** [comment]
What is the definition of `doSomething` ?

**Comment by chuwy** [comment]
Here's completely self-contained example:

```scala
import cats.implicits.*
import cats.effect.Concurrent
import _root_.io.github.iltotore.iron.*
import _root_.io.github.iltotore.iron.constraint.string.*

type Name = String :| Alphanumeric

final case class Person(name: Name)

def test[F[_]: Concurrent](str: String): F[Person] =
  Concurrent[F].fromEither(Either.catchNonFatal(str.refine[Alphanumeric])).map(n => Person(n))
```

What's interesting is that if I remove `F[_]` and just map an `Either` it compiles just fine.

**Comment by chuwy** [comment]
`Concurrent[F].fromEither(...)` just lifts `Either[Throwable, A]` into `F[A]`.

**Comment by chuwy** [comment]
Another interesting observation - if I replace `F[_]` with `IO` - it works.

**Comment by chuwy** [comment]
This one fails:

```scala
def test[F[_]: Monad](str: String): F[Person] =
  for {
    _ <- Monad[F].unit
    name = str.refine[Alphanumeric]
  } yield Person(name)
```

This one doesn't:

```scala
def test[F[_]: Monad](str: String): F[Person] =
  for {
    _ <- Monad[F].unit
  } yield Person(str.refine[Alphanumeric])
```

**Comment by chuwy** [comment]
In scala console:

```
-- Error: ----------------------------------------------------------------------
15 |  } yield Person(name)
   |                 ^^^^
   |Cannot refine non full inlined input at compile-time.
   |To test a constraint at runtime, use the `refined` extension method.
   |
   |Note: Due to a Scala limitation, already-refined types cannot be tested at compile-time (unless proven by an `Implication`).
   |
   |Inlined input: name
   |----------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from rs$line$1:15
    ----------------------------------------------------------------------------
1 error found
```

**Comment by Iltotore** [comment]
From what I understand now, it seems that the type of `name` is for some reasons reduced to `String` in the for comprehension which would be (if I'm right) a bug in Scala's for desugaring. Can you try with flatMap/map?

**Comment by chuwy** [comment]
This one fails:

```scala
def test[F[_]: Monad](str: String): F[Person] =
  Monad[F].unit
    .map(_ => str.refine[Alphanumeric])
    .map(name => Person(name))
```

This one doesn't:

```scala
def test[F[_]: Monad](str: String): F[Person] =
  Monad[F].unit
    .map { _ =>
      val name = str.refine[Alphanumeric]
      Person(name)
    }
```

I agree with you that it's likely something in dotty, but I'd really appreciate an advice on where I can fill a bug as I don't have much knowledge of Iron (tried it for the first time today) nor dotty compile-time magic.

**Comment by chuwy** [comment]
Funny. Making `F` contravariant solves the problem. This one works:

```scala
def test[F[-_]: Monad](str: String): F[Person] =
  Monad[F].unit
    .map(_ => str.refine[Alphanumeric])
    .map(name => Person(name))
```

**Comment by Iltotore** [comment]
> Funny. Making F contravariant solves the problem.

As you said: it's funny :sweat_smile: 

What if you pass explicitly the generic types to `map` like `map[String :| Alphanumeric]`?

**Comment by Iltotore** [comment]
> 'd really appreciate an advice on where I can fill a bug as I don't have much knowledge of Iron (tried it for the first time today) nor dotty compile-time magic.

For questions, you can ask in the Scala offcial Discord server. For Scala 3 issues, you should file to https://github.com/lampepfl/dotty

**Comment by chuwy** [comment]
Before fill in an issue for dotty, I just wanted to investigate the internals a bit (I know nothing about macro, compilers nor inlining).

The only place that can cause this compile-time error is [this](https://github.com/Iltotore/iron/blob/fcf4371e9e49f168dce5ea635c60ace0737bb421/main/src/io/github/iltotore/iron/conversion.scala#L19). And I find it very strange that something that should be called only on a constant is called on clearly a runtime value. So, are we sure it's non-Iron bug and has something to do with reducing inside `F[_]`?

**Comment by Iltotore** [comment]
It's not because the implicit conversion is triggered by Scala only if the types do not match. Since you already refined via `refine` your type and assuming Person takes a `String :| Alphanumeric` it will never be triggered if the types correspond. This means that Scala widen the type too much (aka to `String`). I will do some tests once at home.


It might be interesting to display the input type when the constraint is not evaluable at compile time.

**Comment by Iltotore** [comment]
Update: this code works:
```scala
def test[F[_]: Monad](str: String): F[Person] =
  Monad[F].unit
    .map[String :| Alphanumeric](_ => str.refine[Alphanumeric])
    .map(name => Person(name))
```

So it really looks like a Scala type inference issue.

**Comment by chuwy** [comment]
Ok, submitted a ticket and pinged you there https://github.com/lampepfl/dotty/issues/16987.

I'm not sure what I wrote there make any sense, so it would be great if you chimed in.
