### ISSUE TITLE
Suggestion: support incremental refine/refineFurther with explicit parameter

### ISSUE THREAD

**Issue by GiGurra** [Iltotore/iron#106]
Right now it is not possible to incrementally and explicitly refine, as far as I can tell.
This is something I find needing all the time (i want to append more constraints as data travels through my application, without discarding old constraints, or having to re-type them).

I've never written any real scala3 inlines, macros or such before, so I'm sure this is not the most efficient way of solving it, but I found the following useful - maybe it can give you some ideas on how it could be done in an elegant/proper way?:

```
  extension [Src](value: Src)
    inline def refineZIO[C](using inline constraint: Constraint[Src, C]): IO[String, Src :| C] =
      value.refineValidation[C].toZIO

  extension [Src, Cstr](value: Src :| Cstr)
    inline def refineFurtherZIO[C](using inline constraint: Constraint[Src, C]): IO[String, Src :| (Cstr & C)] =
      (value: Src).refineZIO[C].map(_.asInstanceOf[Src :| (Cstr & C)])
    inline def refineFurtherEither[C](using inline constraint: Constraint[Src, C]): Either[String, Src :| (Cstr & C)] =
      (value: Src).refineEither[C].map(_.asInstanceOf[Src :| (Cstr & C)])
    inline def refineFurtherOption[C](using inline constraint: Constraint[Src, C]): Option[Src :| (Cstr & C)] =
      (value: Src).refineOption[C].map(_.asInstanceOf[Src :| (Cstr & C)])
    inline def refineFurther[C](using inline constraint: Constraint[Src, C]): Src :| (Cstr & C) =
      (value: Src).refine[C].asInstanceOf[Src :| (Cstr & C)]

```

This allows me to further refine already refined types, with a simple syntax (replace my naming and impl with something you prefer!) and append more and more refinements as I go, without discarding the original one

example

```
for {
  x1           <- 0.refineZIO[Less[1] // Int :| Less[1]
  _            <- foo1(x1)
  _            <- bar1(x1)

/// data travels further through the application, many method calls, storage, read from storage, etc
  x2           <- x1.refineFurtherZIO[Less[2]] // Int :| (Less[1] & Less[2])
  _            <- foo2(x2)
  _            <- bar2(x2)

/// data travels further through the application, many method calls, storage, read from storage, etc
  x3           <- x2.refineFurtherZIO[Less[3]] // Int :| (Less[1] & Less[2] & Less[3])
  _            <- foo3(x3)
  _            <- bar3(x3)
} yield ()
```

If there is an existing way to append constraints like this that I'm not seeing, please let me know

**Comment by Iltotore** [comment]
Indeed, the ability to refine further while still keeping current refinements looks like an important feature to me.

I think there might be a better approach to solve this problem by adding a type "proxy" for `IronType`.

Before:
```scala
opaque type IronType[A, C] <: A = A
type :|[A, C] = IronType[A, C]
```

After:
```scala
opaque type IronTypeImpl[A, C] <: A = A

type IronType[A, C] = A match
  case IronType[A, current] => IronType[A, current & C]
  case _ => IronType[A, C]

type :|[A, C] = IronType[A, C]
```

This way, there will be no need to create a `refine...Further` function for each existing refinement method:
```scala
val x: Int :| Positive = 5.refine
val y: Int :| (Positive & Odd) = x.refine //(Int :| Positive) :| Odd <=> Int :| (Positive & Odd)
```

Source compatibility should not break and AFAIK (I need to check it) binary should also be ok since all these types desugar to `A` post compilation. TASTy compatibility __might__ break however. I will have to test it.

Would this approach solve your problem or am I missing something?

**Comment by GiGurra** [comment]
> Indeed, the ability to refine further while still keeping current refinements looks like an important feature to me.
> 
> I think there might be a better approach to solve this problem by adding a type "proxy" for `IronType`.
> 
> Before:
> 
> ```scala
> opaque type IronType[A, C] <: A = A
> type :|[A, C] = IronType[A, C]
> ```
> 
> After:
> 
> ```scala
> opaque type IronTypeImpl[A, C] <: A = A
> 
> type IronType[A, C] = A match
>   case IronType[A, current] => IronType[A, current & C]
>   case _ => IronType[A, C]
> 
> type :|[A, C] = IronType[A, C]
> ```
> 
> This way, there will be no need to create a `refine...Further` function for each existing refinement method:
> 
> ```scala
> val x: Int :| Positive = 5.refine
> val y: Int :| (Positive & Odd) = x.refine //(Int :| Positive) :| Odd <=> Int :| (Positive & Odd)
> ```
> 
> Source compatibility should not break and AFAIK (I need to check it) binary should also be ok since all these types desugar to `A` post compilation. TASTy compatibility **might** break however. I will have to test it.
> 
> Would this approach solve your problem or am I missing something?

I guess I have two goals:
1. being able to specify the refinement explicitly (instead of inferred through a cast/assignment like your example)
2. Ensuring the runtime refinement cost/test is only executed for the additionally refined condition

goal 1 is the most important (since I will be creating domain specific constraints on my types, for example proofs that domain objects have reached certain states)

**Comment by Iltotore** [comment]
This should be possible with the type alias/proxy solution. I will also need to experiment to ensure the compiler infers the right types.

**Comment by GiGurra** [comment]
> This should be possible with the type alias/proxy solution. I will also need to experiment to ensure the compiler infers the right types.
> 
> I will first finish #66 before experimenting but I'm pretty confident if will work.

Thanks! :)

**Comment by Iltotore** [comment]
After experimentations, it seems that this cannot be resolved using a match type because `A` and `A :| B` are not disjoincts, causing the compiler to fail. Implicit conversions work but are not powerful enough to emulate this behaviour.

I your first approach (using `refineFurther`) is probably the best at the moment.

**Comment by Iltotore** [comment]
The PR is almost done but I have some concerns about the name of some methods. For example how would you call a method that turns `A :| C1 :| C2` to `A :| (C1 & C2)` and its reciprocal?

**Comment by Iltotore** [comment]
I need an example of a use case of `refineFurther`s methods for the documentation.
