### ISSUE TITLE
Strange implicit error using opaque types

### ISSUE THREAD

**Issue by vbergeron-ledger** [Iltotore/iron#110]
**Describe the bug**
Scala environment: All
Scala version: 3.2.2
Iron version: 2.0.0

**Reproduction steps**
Given this setup (so encoding of newtypes using a wraper trait overrided by an opaque type) : 
```scala
  trait Wrap:
    type T

  trait Newtype[A] extends Wrap:
    opaque type T = A

    inline def apply(in: A): T = in

    extension (value: this.T) //
      inline def unwrap: A = value

  case object Money extends Newtype[Long :| GreaterEqual[0]]

  val foo = Money(123)
```

**Expected behavior**
Everything compile fine and we got strong, 0 cost type safety.

**Current behavior**
Compilation fails with a strange implicit error : 
```
Could not find implicit AppliedType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class iltotore)),object iron),Constraint),List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Long), AppliedType(TypeRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class iron)),object constraint),any),StrictEqual),List(ConstantType(Constant(0))))))
```
The inlines does not appear to chane the result. I am investigating bisecting more the error cause.

**Comment by vbergeron-ledger** [comment]
More about the issue : The error does not appear when using "Atom" constraints, like `Greater[0]`, but only shows up when a composite constant (`&` or `|`) is used.

**Comment by Iltotore** [comment]
It works when passing a long literal to `GreaterEqual`:
```scala
trait Wrap:
  type T

trait Newtype[A] extends Wrap:
  opaque type T = A

  inline def apply(in: A): T = in

  extension (value: this.T) //
    inline def unwrap: A = value

case object Money extends Newtype[Long :| GreaterEqual[0L]]

val foo = Money(123)
```

([Scastie](https://scastie.scala-lang.org/5rUG80jgT3i3Dtfo8L3sxg))

After investigation, it seems that the bug comes from `StrictEqual` which is too restrictive: for `A :| StrictEqual[V]`, ` V`  must be a subtype of `A`.

This should easily (and without breaking anything) fixed by removing this restriction since it is actually not relevant.
