### ISSUE TITLE
Add companion ops for refined "new types"

### ISSUE THREAD

**Issue by Iltotore** [Iltotore/iron#117]
Refined has a trait called `RefinedTypeOps` which enables users to create their own zero-additional-cost types on top of refined types:

```scala
type Age = Int Refined Positive
object Age extends RefinedTypeOps[Age, Int]

val age: Age = Age(18)
val invalidAge: Age = Age(-15) //Compile-time error
```

For now, Iron does not provide such elegant mechanism for "refined new types" and people combine it with libraries like Sprout.

Iron could provide something similar:

```scala
type Age = Int :| Positive
object Age extends RefinedTypeOps[Int, Age] //Or better: RefinedTypeOps[Age]
```

It would synergize greatly with opaque types:

```scala
opaque type Temperature = Double :| Positive
object Temperature extends RefinedTypeOps[Double, Temperature]

opaque type Moisture = Double :| Positive
object Moisture extends RefinedTypeOps[Double, Moisture]
```
```scala
val temperature = Temperature(25)
val moisture = Moisture(4)

val invalidTemperature: Temperature = Moisture(5) //Error at compile-time because Moisture not <:< Temperature, even if they're both Double :| Positive
```

Finally, extension methods would allow libraries to attach custom methods to the companion:

```scala
val tempEither: Either[String, Temperature] = Temperature.either(15)
val tempValidation: Validation[String, Temperature] = Temperature.validation(15) //From ZIO Module
// etc...
```

**Comment by antonkw** [comment]
@Iltotore 
Hi!
I actively used refined (without `RefinedTypeOps` though). And looking for Iron as alternative to refined+newtypes combination.
"good first issue" label nudges me to give it a try :)

Any recommendations on what I should study (in the lib) before tackling the task itself?

**Comment by antonkw** [comment]
Need help with understanding how constraints supposed to work.

I played around with the snippet:
```
class RefinedTypeOps[A, C]

extension [A, C](ops: RefinedTypeOps[A, C]) {
  inline def from(a: A)(implicit c: Constraint[A, C]): Either[String, A :| C] = a.refineEither[C]
}
```

It works for atomical predicates but not for iron types like `type Temperature = Int :| Positive`.

I expected to find clues in `refineEither`-like functions because I was thinking that `2.refineEither[Temperature]` would work. But it works with predicates as well.

I can't state any particular question but it is somewhere around "should be IronType decomposed to use Constraint for IronType's predicate?"

**Comment by antonkw** [comment]
@Iltotore 
https://github.com/Iltotore/iron/pull/118 - please take a look at the comments (in the code).

`RefinedTypeOps` looks in the following way:
```scala
extension [A, C](ops: RefinedTypeOps[A, IronType[A, C]])
  inline def either(a: A)(using inline constraint: Constraint[A, C]): Either[String, A :| C] = a.refineEither[C]
  inline def apply(inline value: A)(using inline constraint: Constraint[A, C]): A :| C =
    autoRefine(value)
```

So, constructing is enabled:
```
val result: Either[String, Temperature] = Temperature.either(2.0)
val temperatureFromApply: Temperature = Temperature(2)
```

But adding `opaque` brakes compiling.
Even `val t: Temperature = 2` stops to work, hence I not sure if it is something that should be tackled in terms of the feature.

Am I missing something?

**Comment by Iltotore** [comment]
> Even val t: Temperature = 2 stops to work, hence I not sure if it is something that should be tackled in terms of the feature.

This is intented.

About the `apply` and `either` methods, does the error still occur if you define them inside the trait instead of making them extension methods?
