### ISSUE TITLE
Fake constraint for newtypes with no underlying validation

### ISSUE THREAD

**Issue by antonkw** [Iltotore/iron#122]
`RefinedTypeOps` and accessing inner values of opaque types (with `value` call) make iron very good in domain modeling.

One potentially missing part is usage without actual validation (to simply separate value types).

I suggest introducing a fake constraint with easy runtime construction.

Not sure about the naming. I like `Pure` or `Newtype` 

Ex.
```scala
opaque type FirstName = String :| Pure
object FirstName extends RefinedTypeOps[FirstName]
```

And runtime is safe and straightforward.
```scala
val firstName: FirstName = FirstName.pure(anyRuntimeInput)
```

What is important is if the user refactors type to  `String :| ValidUUID` then `pure` stops compiling and requires updates.

**Comment by Iltotore** [comment]
`True` seems to be the constraint you're looking for.

**Comment by antonkw** [comment]
@Iltotore 
Yes, when I played around, True is an exact implementation in terms of predicate logic.

The naming is not precise, though. It doesn't reflect the notion of "let use me if you just want to create a lightweight wrapper to have need domain model and don't need validation at all"

> I don't really see the difference with apply provided by RefinedTypeOps.

The emphasis here is unlocking easy creation for runtime values. Please take a look at the example above.

And with `apply` the following won't compile:
```
type LastName = String :| True
object LastName extends RefinedTypeOps[LastName]
val anyString: String = ""
val value = LastName(anyString) // Cannot refine non full inlined input at compile-time.
```

The options are to use `LastName.applyUnsafe` (or assume), which won't prevent from changing Constraint to something that really can fail.

**Comment by Iltotore** [comment]
This issue was an additional restriction which is probably not needed anymore. Fixing it should remove the need to create a `pure` method.

I will be busy for the next weeks but will look at it ASAP.

**Comment by Iltotore** [comment]
See #125
