### ISSUE TITLE
Cannot follow documentation example in version 2.1.0

### ISSUE THREAD

**Issue by etorres** [Iltotore/iron#126]
Hi,

I'm following this example from the [documentation](https://iltotore.github.io/iron/docs/getting-started.html) but I cannot find the type `RefinedTypeOps` in latest version of the library:

`opaque type Temperature = Double :| Positive`
`object Temperature extends RefinedTypeOps[Temperature]`

All imports are also included.

Scala environment: JVM
Scala version: 3.3.0
Iron version: 2.1.0

Am I doing something wrong? Thanks!

**Comment by Iltotore** [comment]
Hi.

This feature will be included in the next release (probably coming this month or early July). I am currently working on this section in branch `docs/rework-documentation`.

As far as I can tell, you're doing it right. If you want to test it you can use the latest nightly.

Currently, you have on Scaladex the API docs for each version but not the "static" documentation (guides, getting started etc...). Might be worth an issue.

Did I answer your question?

**Comment by etorres** [comment]
Totally yes, that's just the answer I needed.

Thanks for answering so quickly.
