### ISSUE TITLE
Not found: type RefinedTypeOps

### ISSUE THREAD

**Issue by ajaychandran** [Iltotore/iron#127]
**Describe the bug**
Scala environment: JVM/Scala.JS/ScalaNative
Scala version: 3.3.0
Iron version: 2.1.0

**Reproduction steps**
[Scastie](https://scastie.scala-lang.org/MJY5iQz4SuuSkNxWkSciTA)
```scala
import io.github.iltotore.iron.*
import io.github.iltotore.iron.constraint.numeric.Positive

opaque type Temperature = Double :| Positive
object Temperature extends RefinedTypeOps[Temperature]
```

**Expected behavior**
The code compiles and behaves as per [documentation](https://iltotore.github.io/iron/docs/getting-started.html#companion-object).

**Current behavior**
Compiler error
```
Not found: type RefinedTypeOps
```

**Comment by Iltotore** [comment]
Hi.

Funnily enough, [the same question has been posted today](https://github.com/Iltotore/iron/issues/126).

The static documentation (/docs/... page) is synchronized with the main branch, not the current release. `RefinedTypeOps` is a feature of the next version, not released yet.

If you want to try `RefinedTypeOps` now, you should pick a nightly version. The latest nightly is `2.1.0-3-69fb90-SNAPSHOT`.

I will close this issue. If you think I misunderstood something, feel free to open another one.

**Comment by ajaychandran** [comment]
Thanks for the quick turnaround.
