### ISSUE TITLE
Should we keep constraints for Java's BigInteger/BigDecimal?

### ISSUE THREAD

**Issue by Iltotore** [Iltotore/iron#145]
This PR #136 brings constraints for BigInt/BigDecimal and their Java counterpart in the standard constraints library.

Since Scala already has BigInt and BigDecimal, I don't think we need to support Java's ones too. @ajaychandran, since you're the author of the PR mentioned above, what's your opinion?

**Comment by ajaychandran** [comment]
In hindsight, I probably should not have added it given Java numeric boxed types are not supported.
Feel free to remove the associated instances.
