### ISSUE TITLE
Is Show[A] really needed to summon Meta[A :| C] instances for the doobie support

### ISSUE THREAD

**Issue by rreckel** [Iltotore/iron#205]
Hi,

Considering the following in the doobie.scala file:
```
  inline given[A, C] (using inline meta: Meta[A])(using Constraint[A, C], Show[A]): Meta[A :| C] =
    meta.tiemap[A :| C](_.refineEither)(identity)
```

Is cats.Show[A] really needed?
Using postgres support with `LocalDateTime`, this refinement will not work, as there are no default `Show[LocalDateTime]` instances in cats.

Adding something like `given Show[LocalDateTime] = _.toString` will work, but this is confusing, as it's not obvious that a Show instance is needed to sommon the Meta instance.

Thanks,
Roland

**Comment by Iltotore** [comment]
It also look like an uneeded required instance to me. I will check if it is required or not once available.

**Comment by vbergeron-ledger** [comment]
See https://github.com/tpolecat/doobie/blob/68cc2bddfddda60f37e95022a2de0d7e5ff5306b/modules/core/src/main/scala/doobie/util/meta/meta.scala#L33, Show[A] is needed to build the Get instance.
