### ISSUE TITLE
Use fewerBraces in Iron codebase

### ISSUE THREAD

**Issue by Iltotore** [Iltotore/iron#210]
Iron uses Scala 3's identation-based control syntax. Now that it uses Scala 3.3.1, we can use [fewer braces](https://docs.scala-lang.org/sips/fewer-braces.html).

It should be easy to migrate the syntax:
- Upgrade ScalaFMT
- Enable fewerBraces in the config

**Comment by zaxxel** [comment]
Hello! Tell me, please, is it necessary to format all existing code? I'm asking because with the current configuration and version of the library, the formatting check returns 58 misformatted files. If it is updated to 3.8.1, then 12 more will be added.

**Comment by Iltotore** [comment]
Formatting the existing code of Iron is not necessary but I believe it is welcome and I don't see any cons to do it: this will not break any kind of compatibility and the major part of files to reformat are unit tests which use Scala 3.1's "partial few braces" syntax.
