### ISSUE TITLE
Add NonEmptyString type

### ISSUE THREAD

**Issue by dagmendez** [Iltotore/iron#213]
Hello 👋🏼 

Have you consider including a `NonEmpty` as a `string` constrain?

In the project I am working right now we have defined the type as follows:

`type NonEmptyString = String :| Not[Empty]`

We use it as a control type until we come up with a better refinement. It can be useful for early phases of design.

Thank you!

**Comment by Iltotore** [comment]
I'm unsure about the goal of it. `Empty` implies `Blank` (althrough the given `Implication` is not present in the codebase) so `Not[Blank]` already implies `Not[Empty]`.

Therefore, `NonEmpty` is just `Not[Empty]` with a description so what is its purpose compared to just using `Not[Empty]`?

**Comment by Iltotore** [comment]
Closed due to inactivity. See #214
