### ISSUE TITLE
Change color of error message

### ISSUE THREAD

**Issue by Iltotore** [Iltotore/iron#228]
The "aqua" ANSI color used for error messages lacks of readability in [Scastie](https://scala-lang.org/). It might be worth to change it to a more readable color on most common editors (Scastie, VSCode, Intellij...).

**Comment by zaxxel** [comment]
Hi! Perhaps you meant `CYAN`, not `aqua`?  Can I replace it with `MAGENTA`( `#FF1FFF`)? I think it should read well in both light and dark themes.

**Comment by Iltotore** [comment]
Tested on Scastie and other terminals. It is readable to me so go ahead 👍
