### ISSUE TITLE
deprecation warning does not show for `refine`

### ISSUE THREAD

**Issue by 2m** [Iltotore/iron#229]
Scala environment: JVM
Scala version: 3.4.0
Iron version: 2.5.0

Deprecation warnings are not generated for `refine` usage.

```scala
//> using scala 3.4.0
//> using dep io.github.iltotore::iron:2.5.0
//> using option -deprecation

import io.github.iltotore.iron.*
import io.github.iltotore.iron.constraint.numeric.*

def log(x: Double :| Positive): Double =
  Math.log(x) // Used like a normal `Double`

val runtimeValue: Double = 1.9
log(runtimeValue.refine)
```

Output:
```
Compiling project (Scala 3.4.0, JVM (21))
Compiled project (Scala 3.4.0, JVM (21))
```

An example of deprecated method usage from another library where deprecation warning shows up in `scala-cli`:

```scala
//> using scala 3.4.0
//> using dep com.monovore::decline:2.4.1
//> using option -deprecation

import com.monovore.decline.*

object MyApp
    extends CommandApp(
      name = "my-app",
      header = "This is a standalone application!",
      main = Opts.flag("fantastic", "Everything is working.")
    )

MyApp.main(Array.empty)
```

Output:
```
Compiling project (Scala 3.4.0, JVM (21))
[warn] ./decline.sc:14:1
[warn] method main in class CommandApp is deprecated since 0.3.0: 
[warn] The CommandApp.main method is not intended to be called by user code.
[warn] For suggested usage, see: http://monovore.com/decline/usage.html#defining-an-application
[warn] MyApp.main(Array.empty)
[warn] ^^^^^^^^^^
Compiled project (Scala 3.4.0, JVM (21))
```

The only difference I see is that `decline` used [`since`](https://github.com/bkirwi/decline/blob/9e676f38f0b4b6b378069f19f133eefcc2836d12/core/shared/src/main/scala/com/monovore/decline/CommandApp.scala#L45-L50) in the `deprecated` annotation.

**Comment by Iltotore** [comment]
> The only difference I see is that decline used [since](https://github.com/bkirwi/decline/blob/9e676f38f0b4b6b378069f19f133eefcc2836d12/core/shared/src/main/scala/com/monovore/decline/CommandApp.scala#L45-L50) in the deprecated annotation.

I think it's either this or `deprecated` does not play well with inline methods.

**Comment by 2m** [comment]
Yea, that's right. Just tried in in my local project, and as soon as I add `inline`, deprecation warning disappears.

**Comment by Iltotore** [comment]
I think you should open an issue on https://github.com/scala/scala3
