### ISSUE TITLE
Missing 'iron-pureconfig' artifact

### ISSUE THREAD

**Issue by shubbush** [Iltotore/iron#274]
**Describe the bug**
Scala environment: JVM/Scala.JS/ScalaNative
Scala version: 3.4.1
Iron version: 2.6.0

**Reproduction steps**
The steps to reproduce the described issue
Add 'iron-pureconfig' dependency:
```
libraryDependencies += "io.github.iltotore" %% "iron-pureconfig" % "2.6.0"
```

**Expected behavior**
Artifact is available. 

**Current behavior**
Artifact is not found.

**Comment by Iltotore** [comment]
Indeed it was not published. I'll check the cause once available and manually publish the missing version.

**Comment by Iltotore** [comment]
Found the "problem". Actually, the Pureconfig support was added **after** the release of 2.6.0. It will land in the next release, probably 3.0.0
