### ISSUE TITLE
Newtype method option is not accessible under the test directory

### ISSUE THREAD

**Issue by valydia** [Iltotore/iron#278]
**Describe the bug**

When I defined [newtype with no constraint](https://iltotore.github.io/iron/docs/reference/newtypes.html), I am not able to use the refinement method from the `test` directory

**Environment**
* Scala: JVM
* Scala version: 3.5.2
* Iron version: 2.6.0

**Reproduction steps**

The structure of the project is as follows:
```bash
 >tree src
src
├── main
│   └── scala
│       ├── Main.scala
│       └── com
│           └── example
│               ├── Example.scala
│               └── mytypes.scala
└── test
    └── scala
        └── com
            └── example
                ├── Example.scala
                └── ExampleSpec.scala
```
Both `Example.scala` files are identical and here is their content:
```scala
package com.example

import mytypes.MyLong

object Example:

  def foo: Option[MyLong] = {
    val myLong = 3L
    MyLong.option(myLong)
  }
```

And here is `mytypes` content:

```scala
package com.example

import io.github.iltotore.iron.*

object mytypes {

  opaque type MyLong <: Long :| Pure = Long :| Pure
  object MyLong extends RefinedTypeOps.Transparent[MyLong]

}
```
Here is a link to a [reproducible  example](https://github.com/valydia/iron-not-working-in-test)

**Expected behavior**
Running the following command should allow the test to run successfully:
```bash
sbt test
```

**Current behavior**

When I run `sbt test`, the `Example.scala` file under `test` fails to compile with the following error:
```
[error] -- [E008] Not Found Error: /Users/valydia/Workspace/iron-not-working-in-test/src/test/scala/com/example/Example.scala:9:11 
[error] 9 |    MyLong.option(myLong)
[error]   |    ^^^^^^^^^^^^^
[error]   |value option is not a member of object com.example.mytypes.MyLong, but could be made available as an extension method.
[error]   |
[error]   |The following import might make progress towards fixing the problem:
[error]   |
[error]   |  import io.github.iltotore.iron.autoRefine
[error]   |
[error] one error found
```

**Workaround**

1. If I copy the `mytypes.scala` file into the `test` directory, the tests run successfully.
2. An even better one is to define `MyLong` as:
```
object MyLong extends RefinedTypeOps[Long, Pure, MyLong]
```

**Comment by Iltotore** [comment]
Hello!

The problem here is that you're using `RefinedTypeOps.Transparent` which is only for transparent (aka non-opaque) type aliases. Due to a compiler limitation, you have to use the more boilerplate-ish `RefinedTypeOps[Long, Pure, MyLong]`.

FYI I'm working on a more concise newtipe definition in #253 for 3.0.0
