### ISSUE TITLE
6

### ISSUE THREAD

**Issue by Emacewosc** [Iltotore/iron#47]
**Describe the bug**
Scala environment: JVM/Scala.JS/ScalaNative
Scala version:
Iron version:

**Reproduction steps**
The steps to reproduce the described issue
- Step 1
- Step 2

**Expected behavior**

**Current behavior**
A clear and concise description of what actually happens

**Comment by Iltotore** [comment]
I assume it was an error. If you really wanted to open an issue, feel free to reopen this one with a good description.
