### ISSUE TITLE
Support for `jsoniter-scala` codecs

### ISSUE THREAD

**Issue by kyri-petrou** [Iltotore/iron#82]
**Is your feature request related to a problem? Please describe.**
[jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala) is the fastest json parser available in Scala. It's becoming quite popular, and several libraries already provide support for it (e.g., [tapir](https://tapir.softwaremill.com/en/latest/endpoint/json.html#jsoniter-scala), [sttp](https://sttp.softwaremill.com/en/latest/json.html#jsoniter-scala), [caliban](https://github.com/ghostdogpr/caliban) ([WIP](https://github.com/ghostdogpr/caliban/pull/1527))).

It would be good if Iron provided support for it same way that it does for circe / zioJson.

The implementation for jsoniter-scala is slightly less straightforward than circe / zioJson since it makes heavy use of macros for derivation and doesn't provide implicits for standard types. This could easily dissuade a user from using Iron if they can't figure the interop out easily / quickly.

**Describe the solution you'd like**
Very similar to the circe / zioJson approach, provide a given / method with which the user can create codecs for jsoniter-scala.

If you think that this is something that you would like to add to the library, I can make a PR for it (I already have a working example - just let me know and I'll open a PR)

**Comment by Iltotore** [comment]
Looks good to me and given the nature of the module (given instances like Circe/ZIO Json), it should not really increase the maintenance cost. 👍 

I will have to be careful to keep the number of "official" modules reasonable. (i.e Scalacheck support)

**Comment by Iltotore** [comment]
@kyri-petrou do you want create the jsoniter module?

**Comment by Iltotore** [comment]
Don't worry for the time. I just wasn't sure if someone was already working on this issue or not 😛
