### ISSUE TITLE
`URLLike` constraint fails on `%` characters

### ISSUE THREAD

**Issue by kyri-petrou** [Iltotore/iron#85]
**Describe the bug**
Scala environment: JVM
Scala version: `3.2.1`
Iron version: `2.0.0-RC1-19-cb7d80-DIRTY12775d8a-SNAPSHOT` (latest snapshot)

The `%` is a valid URL character, which is used when encoding strings into URLs. For example, `%20` can used to represent a space

**Reproduction steps**

```scala
val url: String |: URLLike = "http://example.com/?q=with%20space" // Doesn't compile
val url: String |: URLLike = "http://example.com/?q=with+space" // compiles
```

**Expected behavior**
Should compile since it's a valid URL

**Current behavior**
Doesn't compile

**Comment by kyri-petrou** [comment]
Thanks for sorting this out so quickly! I also noticed now the constraint allows for `localhost` - thanks for that!

I gave the changes a go but it seems that they introduced another bug. The new assertion fails when the port number is defined, e.g., `http://example.com:8080`. Would you like me to create a separate issue for this?

**Comment by Iltotore** [comment]
I think it's ok to just reopen this issue.

**Comment by kyri-petrou** [comment]
@Iltotore  do snapshot versions get automatically published or do you need to publish them manually? I can't seem to find a version with the latest fix

**Comment by Iltotore** [comment]
They're are published each night if commits were done (to avoid one-artifact-by-merge spamming) in the last 24 hours. It will be there at 00:00 UTC+0.

**Comment by kyri-petrou** [comment]
Awesome, thanks!
